name: CI - infra only (hello + build & push images, no deploy)

on:
  push:
    branches: [ "infra" ]
    paths:
      - "code/takata_frontend/**"
      - "code/takata_backend/**"
      - "infra/**"
      - ".github/workflows/**"
  pull_request:
    branches: [ "infra" ]
    paths:
      - "code/takata_frontend/**"
      - "code/takata_backend/**"
      - "infra/**"
      - ".github/workflows/**"

permissions:
  contents: read
  packages: write
  id-token: write

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ghcr.io/${{ github.repository }}     # ex: ghcr.io/org/repo
  PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7    # build multi-arch (inclut RPi)
  DOCKER_TAG: infra                                   # on tagge 'infra' sur cette branche

jobs:
  hello:
    name: Smoke test - Hello World
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "✅ Hello World depuis la CI GitHub (branche infra) !"

  frontend:
    name: Frontend - Lint & Build (Angular)
    runs-on: ubuntu-latest
    needs: hello
    defaults:
      run:
        working-directory: code/takata_frontend
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'code/takata_frontend/package-lock.json'

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Tests (optionnel)
        run: npm test -- --watch=false --browsers=ChromeHeadless || true

      - name: Build prod
        run: npm run build -- --configuration production

      - name: Upload dist (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: angular-dist
          path: code/takata_frontend/dist/**

  backend:
    name: Backend - Tests & Package (Spring Boot)
    runs-on: ubuntu-latest
    needs: hello
    defaults:
      run:
        working-directory: code/takata_backend
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'maven'

      - name: Unit tests
        run: mvn -B -DskipITs test

      - name: Package JAR
        run: mvn -B -DskipTests package

      - name: Upload JAR (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: spring-jar
          path: code/takata_backend/target/*.jar

  build-and-push:
    name: Buildx multi-arch & Push images (:infra)
    runs-on: ubuntu-latest
    needs: [ frontend, backend ]
    steps:
      - uses: actions/checkout@v4

      # Récupère les artefacts (dist Angular + jar Spring)
      - name: Download Angular dist
        uses: actions/download-artifact@v4
        with:
          name: angular-dist
          path: code/takata_frontend/dist
      - name: Download Spring JAR
        uses: actions/download-artifact@v4
        with:
          name: spring-jar
          path: code/takata_backend/target

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Tags → 'infra' + tags utiles (sha, branch)
      - name: Meta backend
        id: meta_backend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_PREFIX }}-backend
          tags: |
            type=raw,value=${{ env.DOCKER_TAG }}
            type=sha,prefix=sha-,format=short
            type=ref,event=branch
      - name: Meta frontend
        id: meta_frontend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_PREFIX }}-frontend
          tags: |
            type=raw,value=${{ env.DOCKER_TAG }}
            type=sha,prefix=sha-,format=short
            type=ref,event=branch

      # Build & push BACKEND
      - name: Build & Push backend
        uses: docker/build-push-action@v6
        with:
          context: ./code/takata_backend
          file: ./code/takata_backend/Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: true          # mets 'false' si tu ne veux pas pousser l'image
          tags: ${{ steps.meta_backend.outputs.tags }}
          labels: ${{ steps.meta_backend.outputs.labels }}

      # Build & push FRONTEND
      - name: Build & Push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./code/takata_frontend
          file: ./code/takata_frontend/Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: true          # mets 'false' si tu ne veux pas pousser l'image
          tags: ${{ steps.meta_frontend.outputs.tags }}
          labels: ${{ steps.meta_frontend.outputs.labels }}
